# Generated by Django 6.0.6 on 2026-07-04 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0004_appointmentchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('subjective_notes', models.TextField(blank=True)),
                ('objective_notes', models.TextField(blank=True)),
                ('assessment_notes', models.TextField(blank=True)),
                ('plan_notes', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='visit', to='scheduling.appointment')),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='employees.employeeprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['doctor_profile', 'status'], name='visits_visi_doctor__3cb7f7_idx'), models.Index(fields=['patient'], name='visits_visi_patient_2cea88_idx'), models.Index(fields=['appointment'], name='visits_visi_appoint_8ffb02_idx'), models.Index(fields=['started_at'], name='visits_visi_started_821fa1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Active')), fields=('doctor_profile',), name='one_active_visit_per_doctor')],
            },
        ),
    ]
