# Generated by Django 6.0.6 on 2026-07-04 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending')], default='Pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='employees.employeeprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='visits.visit')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['patient', 'created_at'], name='billing_inv_patient_9fc9fa_idx'), models.Index(fields=['doctor_profile', 'created_at'], name='billing_inv_doctor__93acae_idx'), models.Index(fields=['status', 'created_at'], name='billing_inv_status_bfbaa4_idx')],
            },
        ),
    ]
