# Generated by Django 6.0.6 on 2026-07-04 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_shifts', to='employees.employeeprofile')),
            ],
            options={
                'ordering': ('employee_profile__user__full_name', 'day_of_week', 'start_time', 'id'),
                'indexes': [models.Index(fields=['employee_profile', 'day_of_week'], name='scheduling__employe_b6c06f_idx'), models.Index(fields=['employee_profile', 'day_of_week', 'is_active'], name='scheduling__employe_7694f6_idx')],
            },
        ),
    ]
