# Generated by Django 6.0.6 on 2026-07-04 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(choices=[('Leave', 'Leave'), ('Sick Leave', 'Sick Leave'), ('Personal', 'Personal'), ('Training', 'Training'), ('Emergency', 'Emergency'), ('Other', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_availability_exceptions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_exceptions', to=settings.AUTH_USER_MODEL)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='employees.employeeprofile')),
            ],
            options={
                'ordering': ('employee_profile__user__full_name', 'start_at', 'id'),
                'indexes': [models.Index(fields=['employee_profile', 'status', 'start_at', 'end_at'], name='scheduling__employe_efdc81_idx'), models.Index(fields=['start_at'], name='scheduling__start_a_8ab4f7_idx'), models.Index(fields=['end_at'], name='scheduling__end_at_737e1e_idx')],
            },
        ),
    ]
