# Generated by Django 6.0.6 on 2026-07-04 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0002_availabilityexception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('visit_type', models.CharField(choices=[('Initial Consultation', 'Initial Consultation'), ('Routine Checkup', 'Routine Checkup'), ('Treatment Continuation', 'Treatment Continuation'), ('Follow-up Visit', 'Follow-up Visit'), ('Emergency Visit', 'Emergency Visit'), ('X-ray Review', 'X-ray Review'), ('Post-treatment Review', 'Post-treatment Review'), ('Cleaning Visit', 'Cleaning Visit')], max_length=40)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Arrived', 'Arrived'), ('Checked-in', 'Checked-in'), ('In Visit', 'In Visit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-show', 'No-show'), ('Postponed', 'Postponed'), ('Needs Reschedule', 'Needs Reschedule')], default='Scheduled', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='employees.employeeprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ('start_at', 'id'),
                'indexes': [models.Index(fields=['doctor_profile', 'start_at', 'end_at'], name='scheduling__doctor__e9a028_idx'), models.Index(fields=['status', 'start_at'], name='scheduling__status_694a78_idx'), models.Index(fields=['patient', 'start_at'], name='scheduling__patient_5e7ed3_idx')],
            },
        ),
    ]
