# Generated by Django 6.0.6 on 2026-07-04 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('scheduling', '0003_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Arrive', 'Arrive'), ('Check In', 'Check In'), ('Cancel', 'Cancel'), ('Mark No-show', 'Mark No-show'), ('Postpone', 'Postpone'), ('Mark Needs Reschedule', 'Mark Needs Reschedule'), ('Reschedule', 'Reschedule')], max_length=40)),
                ('previous_status', models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Arrived', 'Arrived'), ('Checked-in', 'Checked-in'), ('In Visit', 'In Visit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-show', 'No-show'), ('Postponed', 'Postponed'), ('Needs Reschedule', 'Needs Reschedule')], max_length=30)),
                ('new_status', models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Arrived', 'Arrived'), ('Checked-in', 'Checked-in'), ('In Visit', 'In Visit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-show', 'No-show'), ('Postponed', 'Postponed'), ('Needs Reschedule', 'Needs Reschedule')], max_length=30)),
                ('old_start_at', models.DateTimeField(blank=True, null=True)),
                ('old_end_at', models.DateTimeField(blank=True, null=True)),
                ('new_start_at', models.DateTimeField(blank=True, null=True)),
                ('new_end_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='scheduling.appointment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_change_logs', to=settings.AUTH_USER_MODEL)),
                ('new_doctor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_appointment_change_logs', to='employees.employeeprofile')),
                ('old_doctor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_appointment_change_logs', to='employees.employeeprofile')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['appointment'], name='scheduling__appoint_5e60d9_idx'), models.Index(fields=['created_at'], name='scheduling__created_6fd97d_idx')],
            },
        ),
    ]
