# Generated by Django 6.0.6 on 2026-07-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_appointmentchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentchangelog',
            name='action',
            field=models.CharField(choices=[('Arrive', 'Arrive'), ('Check In', 'Check In'), ('Cancel', 'Cancel'), ('Mark No-show', 'Mark No-show'), ('Postpone', 'Postpone'), ('Mark Needs Reschedule', 'Mark Needs Reschedule'), ('Reschedule', 'Reschedule'), ('Start Visit', 'Start Visit'), ('Complete Visit', 'Complete Visit')], max_length=40),
        ),
    ]
