# Generated by Django 6.0.6 on 2026-07-04 18:27

import attachments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=attachments.models.attachment_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('attachment_type', models.CharField(choices=[('X-ray', 'X-ray'), ('Document', 'Document'), ('Other', 'Other')], default='X-ray', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='visits.visit')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['patient', 'created_at'], name='attachments_patient_91b919_idx'), models.Index(fields=['visit', 'created_at'], name='attachments_visit_i_37b162_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='attachments_uploade_565374_idx'), models.Index(fields=['attachment_type', 'created_at'], name='attachments_attachm_fea763_idx'), models.Index(fields=['is_deleted', 'created_at'], name='attachments_is_dele_769f31_idx')],
            },
        ),
    ]
